//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppMag.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;Initial Catalog=\"D:\\KAMIL\\STUDIA II\\APLIKACJA " +
            "MAGISTERSKA\\WPFAPPMAG\\WPFAPPMAG\\LOCALDB.MDF\";Integrated Security=True;;user id=T" +
            "est;password=Test; Timeout=30;Encrypt=False;TrustServerCertificate=False")]
        public string D__KAMIL_STUDIA_II_APLIKACJA_MAGISTERSKA_WPFAPPMAG_WPFAPPMAG_LOCALDB_MDFConnectionString {
            get {
                return ((string)(this["D__KAMIL_STUDIA_II_APLIKACJA_MAGISTERSKA_WPFAPPMAG_WPFAPPMAG_LOCALDB_MDFConnectio" +
                    "nString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=C:\\Users\\Kamil\\AppData\\Local\\" +
            "Microsoft\\Microsoft SQL Server Local DB\\Instances\\MSSQLLocalDB\\xmlDB.mdf;Integra" +
            "ted Security=True")]
        public string xmlDBConnectionString {
            get {
                return ((string)(this["xmlDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=D:\\KAMIL\\STUDIA II\\APLIKACJA " +
            "MAGISTERSKA\\WPFAPPMAG\\WPFAPPMAG\\XMLDB.MDF;Integrated Security=True")]
        public string xmlDBConnectionString1 {
            get {
                return ((string)(this["xmlDBConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\XMLDB.MDF;Int" +
            "egrated Security=True")]
        public string XMLDBConnectionString2 {
            get {
                return ((string)(this["XMLDBConnectionString2"]));
            }
        }
    }
}
